export const userActionTypes = {
  GOOGLE_SIGN_IN_START: "GOOGLE_SIGN_IN_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  AUTH_FAILURE: "AUTH_FAILURE",
  CLEAR_ERROR: "CLEAR_ERROR",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
};
