export const expensesActionTypes = {
  EXPENSES_FAILURE: "EXPENSES_FAILURE",
  SET_EXPENSES: "SET_EXPENSES",
  EDIT_EXPENSE: "EDIT_EXPENSE",
  REMOVE_EXPENSE: "REMOVE_EXPENSE",
  ADD_EXPENSE: "ADD_EXPENSE",
};
